### PR TITLE
Turkish language created

### PR DESCRIPTION
**Pull request by JSerroni**
@ghujka provided the Turkish translation. Could be cool have it added! @reustle 

// Please tag @reustle in your newly created PR

// Please include a screenshot of any visual changes you've made

### CODE REVIEW

**Comment by liquidx** [comment]
Thank you for adding these translations. To make Turkish show up in the language selection, you will need to modify index.js too. Here is an example of what you need to do:

https://github.com/reustle/covid19japan/pull/432/files

**Comment by JSerroni** [comment]
Thanks. I'll give it a shot. :)

**Comment by reustle** [comment]
Hey @JSerroni - Were you able to get to this? If not, no worries at all, we can close the PR for now :) Thank you very much.

**Comment by JSerroni** [comment]
> Hey @JSerroni - Were you able to get to this? If not, no worries at all, we can close the PR for now :) Thank you very much.

Sorry I couldn't. If is okay let's close.

**Comment by reustle** [comment]
Thank you for your contributions!

**Pull request closed without merging**
