### PR TITLE
Get data action

### PR DESCRIPTION
**Pull request by olingern**
This should work if the correct environment variables are provided. I had to duplicate the `cache-sheet` file and the dependencies due to Docker permissions and not being able to reach above the current directory.  
image

Github notes that 5 minutes is the minimum for cron schedules, but I'm seeing 8 minutes. I guess they're still working things out

### CODE REVIEW

**Comment by olingern** [comment]
Also, it looks like requesting a reviewer permissions aren't set up. I'm unable to select a user from the "Reviewers" area

image

**Comment by reustle** [comment]
Thanks so much for this @olingern ! 

We're (@python273 and I) are going through this now, but a bit delayed because [Github has been down](https://www.githubstatus.com/) 😅 

Will comment here once confirmed/tested.

**Comment by reustle** [comment]
Merged! Thanks a ton Nick @olingern - You can see it in _action_ here: https://github.com/reustle/covid19japan/actions

**Comment by olingern** [comment]
@reustle welcome! :rocket:

**Pull request merged**
