### PR TITLE
Fix map redraw

### PR DESCRIPTION
**Pull request by olingern**
@reustle 

Ah, looks like you got to this before me. I removed the add /remove layer in this PR as well.

Maybe, I'll drop 5486af0 from this PR?

What do you think of adding `prettier` in this PR?

### CODE REVIEW

**Comment by reustle** [comment]
I pushed a fix to master, please check the merge conflicts

**Comment by reustle** [comment]
Woah, this pr just got huge, can you please separate prettier into a new PR?

I want to get the map redraw fixed merged asap. A bunch of people still have the embed page loaded on the news websites so the errors are still flooding in, but we can only wait for those ($$ on Sentry though). Thanks

**Comment by olingern** [comment]
Yep

**Comment by reustle** [comment]
image

Indentation error here

**Pull request merged**
