### PR TITLE
Add RTL support along with Farsi

### PR DESCRIPTION
**Pull request by darvishzadeh**
// Please tag @reustle in your newly created PR
This change adds RTL layout along with the Persian language.

- This change only visually affect RTL languages.
- The visual change is basically a root element CSS text direction.
- CSS styles (box sizings) also have been updated to support [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Floating_and_positioning).

// Please include a screenshot of any visual changes you've made
farsi

It would be nice to have a different font as well. The default is hard to read through.

### CODE REVIEW

**Comment by liquidx** [comment]
Thanks for your pull request. I'm a little busy at the moment, hopefully will have time to merge it on the weekend.

**Comment by darvishzadeh** [comment]
any updates? :)

**Comment by liquidx** [comment]
Thanks for the contribution! The RTL support looks good, there are some small glitches with the charts but it maybe because of c3's layout.

**Comment by darvishzadeh** [comment]
Thanks! I will look into getting that fixed as well

**Pull request merged**
