### PR TITLE
English News?

### PR DESCRIPTION
**Pull request by cmod**
// Please tag @reustle in your newly created PR
@reustle — just adding a little english news section at the bottom; perhaps useful? something to consider expanding

### CODE REVIEW

**Comment by reustle** [comment]
Thanks Craig! Maybe this could be a comma-separated list within Helpful Links? `Japan Times, Kyodo News, Asahi Shimbun`

Also, I've already got Motoko Rich covered under the Twitter accounts list. Cheers

**Comment by cmod** [comment]
Perfect.

**Comment by cmod** [comment]
updated; something like this?

**Comment by reustle** [comment]
Thanks! 🙏

**Pull request merged**
