### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by kant**
// Please tag @reustle in your newly created PR

### CODE REVIEW

**Comment by mertd** [comment]
There will be two additional changes needed to make the app usable in a new language:
- Import your translation in `src/data/constants.js` and add to resources in the `LANG_CONFIG` export
- Add to language switcher (@reustle maybe #215 should automatically display all available locales?). Until then, Spanish would be rendered only if the user's browser is set up to display Spanish, or if the page is accessed with `lng=es` as a query parameter

**Comment by reustle** [comment]
Thank you for translating everything!

Yeah I'm sure about adding many languages to the switcher (see #215 for UI) but if it automatically sets itself to Spanish if the users browser is set to Spanish, then they can manually click English / Japanese if they want. Does that sound good?

**Comment by kant** [comment]
@reustle I trust in the whole project, so, go ahead with _your_ plan. Whatever it is your choice, it will be `OK` for my persona.

**Comment by mertd** [comment]
Since #227 is merged, you only need to add "es" to the languages array in `src/i18n/index.js` so that the app actually reads your translation file.

**Comment by mertd** [comment]
#259 is merged and will require you to add "es" to the `LANGUAGES` array as well as a flag emoji to the `FLAGS` array in `src/i18n/index.js`

**Comment by mertd** [comment]
Should I make the necessary changes? I could fork from @kant's branch so their contribution is counted.

**Comment by reustle** [comment]
Sounds good @mertd

**Pull request closed without merging**
