### PR TITLE
Spanish translation fixes

### PR DESCRIPTION
**Pull request by vlumi**
Hi @reustle 

Adding the missing Spanish translation for #359, and removing the couple obsolete entries that were moved under another key (#351).

### CODE REVIEW

**Comment by vlumi** [comment]
The changes have been made to this pull request, but one of the maintainers would first need to merge and release it before the changes appear on the site.

Meanwhile, if you have interest, there are some other missing Spanish translations listed in #351 which could be included here as well...

**Comment by AlanYokohama** [comment]
> 
> 
> The changes have been made to this pull request, but one of the maintainers would first need to merge and release it before the changes appear on the site.
> 
> Meanwhile, if you have interest, there are some other missing Spanish translations listed in #351 which could be included here as well...

Sorry, I can't see them. Would you please tell me how to see the sentences to be translated?

**Comment by vlumi** [comment]
>  Sorry, I can't see them. Would you please tell me how to see the sentences to be translated?

The following are missing for Spanish:
- "languages" ("Languages" In language selector)
- "increment-today" ("Today" in Top 10 Prefectures)
- "increment-yesterday" ("Yesterday" in Top 10 Prefectures)
- "daily" ("Daily" in the legend for Nuevos casos diarios)
- "7-day-average" ("7-day average" in the legend for Nuevos casos diarios)

**Comment by reustle** [comment]
Thanks! Once these final changes are made, I'll merge it in.

**Comment by AlanYokohama** [comment]
Thanks. These are the Spanish translations:
>     * "languages" ("Idiomas" In language selector)
> 
>     * "increment-today" ("Hoy" in Top 10 Prefectures)
> 
>     * "increment-yesterday" ("Ayer" in Top 10 Prefectures)
> 
>     * "daily" ("Diarios" in the legend for Nuevos casos diarios)
> 
>     * "7-day-average" ("Media semanal" in the legend for Nuevos casos diarios)

**Comment by vlumi** [comment]
All updated.

**Pull request merged**
