### PR TITLE
Add Prefecture trajectory visualization

### PR DESCRIPTION
**Pull request by l15n**
Implements https://github.com/reustle/covid19japan/issues/109

Screen Shot 2020-03-28 at 11 22 03 PM

I've set an initial threshold of 50 cases for this chart. This threshold may need to be increased to 100 in coming days.

Hopefully this can give users some context on the relative rate of change of prefectures.

@reustle What do you think? I've tentatively added the chart just above the prefectures table.

In terms of the implementation, there's a fair bit of data manipulation going on. I think it's OK to keep doing this at runtime for now, but if necessary, perhaps the cumulative array can be moved into the data repository.

### CODE REVIEW

**Comment by liquidx** [comment]
One thing though, the chart doesn't look logarithmic. as in expected it to compress between 100 to 1000, but it looks linear to me.

**Comment by reustle** [comment]
👏 Great work! :shipit:

**Comment by l15n** [comment]
> One thing though, the chart doesn't look logarithmic. as in expected it to compress between 100 to 1000, but it looks linear to me.

It is intentionally linear right now. Will change it to logarithmic when the numbers get big enough.

**Comment by l15n** [comment]
Screen Shot 2020-03-29 at 1 18 16 AM

I updated the title and styles after rebasing with master.

**Comment by reustle** [comment]
Looks good, ready to merge?

**Comment by l15n** [comment]
> Looks good, ready to merge?

👍 

Though it looks like if I include the production build `docs/index.js` etc, it is going to conflict every time. Should we leave the production build out of pull requests, and instead update separately, either pushing to master or separate pull requests?

**Comment by l15n** [comment]
I removed the conflicting production build so it should be good to merge. Will need a separate commit to build and put it in production

**Comment by reustle** [comment]
> and instead update separately, either pushing to master or separate pull requests?

Hmm, I think everyone else includes the build of /docs within their PRs, as long as its merged with the latest master there shouldn't be any conflicts? Maybe I'm not understanding you, though.

Thanks! I guess we'll have another PR shortly for the /docs bulid?

**Comment by l15n** [comment]
> Hmm, I think everyone else includes the build of /docs within their PRs, as long as its merged with the latest master there shouldn't be any conflicts? Maybe I'm not understanding you, though.

It's a timing issue where, if Pull Request A and Pull Request B both have `/docs`, and Pull Request A gets merged first, the author of Pull Request B will get a conflict until they can pull master and rebuild. This can get cumbersome because the `/docs` will not merge cleanly, so you need to do something like remove the commit where you did a production build, then build again. 

This isn't a difficult procedure, but does mean that the more people are involved, the more often people will have to re-run `npm run build-prod` multiple times 🤷‍♂

**Pull request merged**
