### PR TITLE
Quick tiny modification to show spread graphs in decimal or log scales

### PR DESCRIPTION
**Pull request by prajdabre**
// Please tag @reustle in your newly created PR
@reustle I have currently put a button to toggle between decimal and log scales. Would this be what you are looking for?

If this is ok then I can do this for all other graphs. Just let me know which ones.

### CODE REVIEW

**Comment by liquidx** [comment]
Thanks for the PR, we really appreciate it.

I took a look at the log graph, while maybe interesting mathematically, it seems like a straight line and not that easy to understand for the average person. We want to keep the graphs simple and understandable.

Unfortunately, I think we will not merge this feature in right now. But again, thank you so much for the PR.

**Comment by prajdabre** [comment]
Hello,

That is perfectly ok. I made this PR because I noticed that someone had raised an issue (#141 ).
Im happy to contribute in any way :)

**Comment by vlumi** [comment]
> We want to keep the graphs simple and understandable.

As a user I would really appreciate the option to see the graphs in logarithmic scale, as the current "Confirmed Case Trajectories by Prefecture" is largely unreadable because the majority of the prefectures are flat on the X axis, due to Tokyo overwhelming the numbers. With logarithmic scale the early increases could be compared between prefectures, to see whether they follow a common curve or not.

Linear scale should probably be the default, as it is more intuitive for seeing the current state.

**Comment by reustle** [comment]
Hello @prajdabre ! Thanks so much for this PR. Unfortunately it didn't get merged, and it is now very far from master. I will close this for now, but we still greatly appreciate the contributions. Thank you.

**Pull request closed without merging**
