### PR TITLE
add new language - Indonesian

### PR DESCRIPTION
**Pull request by fauzanalfi**
add a new language - Indonesian
tag @reustle

### CODE REVIEW

**Comment by liquidx** [comment]
Thank you! I think it would be great. 

If you don't mind merging your change to the latest HEAD, I can consider add this.

**Comment by fauzanalfi** [comment]
@reustle I've merged mine with the latest changes and localize them all to "id". Let me know if there's anything I missed.

**Comment by liquidx** [comment]
Thank you so much for creating the PR and updating it.

I merged another PR that also contributed Indonesian translations yesterday - could you see if there's any additional changes in the PR that is missing from master?

**Comment by fauzanalfi** [comment]
I have checked the changes from the other PR contribution + from master. So, I added some changes on mine to improve the localization. It's good to go.

**Comment by fauzanalfi** [comment]
I also checked the current live Indonesian localization. There are some typos and missing spaces, which are now fixed in this PR. One of the examples is in this string:
image

**Comment by jiprastyo** [comment]
I am new to github and just realized that this pull existed before. yesterday, I did the translation without previously checking in the pull request queue. truly apologize for that. I have improved the translation last night (https://github.com/reustle/covid19japan/pull/329) but I acknowledge that @fauzanalfi's translation is better than mine.
So, to @fauzanalfi , you can just pull only the id.json, as I'd pulled the index.html and other related file yesterday. I will withdraw my latest id.json pull (https://github.com/reustle/covid19japan/pull/329).
Cheers.

**Comment by fauzanalfi** [comment]
Thank you for the acknowledgement, @jiprastyo. I really appreciate it.

**Comment by liquidx** [comment]
Thanks all, could you see if you could resolve the conflicts on this PR? It currently has conflicts that won't allow me to merge it.

**Comment by fauzanalfi** [comment]
Sorry, I missed that part before. All conflicts are fixed now.

**Comment by liquidx** [comment]
Thank you so much, I'm merging this in now.

**Pull request merged**
