### PR TITLE
implement city hover and small refeactor

### LINKED ISSUE #32: Show Prefecture Case Count On Hover
When you hover over a prefecture on the map, show the number of cases

### PR DESCRIPTION
**Pull request by olingern**
Fixes #32.

Builds a lookup from s3 json and then performs lookups on mouse hovers via the geo json's city.

image

I saw that `.map` was being used in a couple of places, but the returned array wasn't being used. Changed those to for loops.

### CODE REVIEW

**Comment by amwfarid** [comment]
@olingern You mentioned in the title "city hover". Would it also happen to resolve #27 as well?

**Comment by reustle** [comment]
We don't quite have city data logged yet in the spreadsheet, but will be working on it. I added a column for it last night, so we will start to see it being added.

**Comment by reustle** [comment]
Great, thanks for implementing this! Here are a few comments.

1. Do you know if a simple way to center the pin on the prefecture always? Would we need to have a defined `center point` for each prefecture, or can we reasonably easily calculate it using prefectures json?

2. I think the label should say something like `12 confirmed cases`

3. Can we somehow not show any popup on prefectures with no cases?

4. Due to the quickly rising cost of hosting Mapbox on the site, #39 is looking like something that will be done quite soon. It might be better to hold off on merging this until that is done? Or we quickly merge it and let it run until we implement the new map. More of an FYI

Only numbers 2 & 3 above are important. Thanks again!

image

**Comment by reustle** [comment]
Ah, sooner than expected https://github.com/reustle/covid19japan/pull/49

**Comment by olingern** [comment]
1. Could be tricky. Maybe it's possible to sort by lat / lng, but doing so doesn't seem super performant. Arbitrarily selecting an index, _i.e. always 0_ would probably work best. I think the geojson would need the center point as a property if desired.

2. Sure, but we would need Japanese, which I'm only mediocre at. Maybe "12 確認しました"  ... [NHK](https://www3.nhk.or.jp/news/html/20200227/k10012303921000.html) seems to be using "感染確認" though. So, in their style, "感染確認12人", but I'm sure any Japanese person would know best.

3. Yah, doable.

4. I see. I can hold off until #49 is done and rebase that over this or close and re-open a new PR.

**Comment by reustle** [comment]
4. 👌 I think this is the best choice, let's jump right back on this as soon as SVG is merged. Thanks again!

**Comment by olingern** [comment]
Closing this for now,

**Comment by reustle** [comment]
Thank you again! We're not so sure about the future of the map yet overall.

**Comment by olingern** [comment]
No prob. I'll try to drop in again and offer some help somewhere else :slightly_smiling_face:

**Pull request closed without merging**
