### PR TITLE
Fixes overflowing Prefectures table making only table scroll

### PR DESCRIPTION
**Pull request by bmaniteja**
@reustle 
Fixes https://github.com/reustle/covid19japan/issues/203

output

### CODE REVIEW

**Comment by reustle** [comment]
Thank you! I think this is already fixed in https://github.com/reustle/covid19japan/pull/217 ?

But your implementation seems simpler. Thoughts @mertd ?

Thanks both

**Comment by mertd** [comment]
This would be nicer because it doesn't need an additional wrapper element, but it also adds scrollbars for me to a lot of other elements:
grafik

**Comment by reustle** [comment]
Yeah it seems this shouldn't be on `section, header, footer {` but instead that table specifically

**Comment by bmaniteja** [comment]
> This would be nicer because it doesn't need an additional wrapper element, but it also adds scrollbars for me to a lot of other elements:
> grafik

oh wow i didn't realise this let me look into this.

**Comment by bmaniteja** [comment]
Fixed it by making auto so that we don't see default scroll

**Comment by reustle** [comment]
I've just merged the other table width fix PR so I think we can safely close this one. Thanks again!

**Pull request closed without merging**
