### PR TITLE
feature / code refactoring

### PR DESCRIPTION
**Pull request by ekreerenko**
// Please tag @reustle in your newly created PR

### CODE REVIEW

**Comment by reustle** [comment]
Hey, this column seems to be missing on your branch but not master, could you please verify?

image

**Comment by reustle** [comment]
Thank you for doing this cleanup? Are these things that we can define in the lint files to ensure that they are enforced moving forward?

**Comment by ekreerenko** [comment]
> Hey, this column seems to be missing on your branch but not master, could you please verify?
> 
> image

Fixed in
https://github.com/reustle/covid19japan/pull/204/commits/a9fa77081942d18a39c7fe326aea485b24f9cd9a

Снимок экрана 2020-04-07 в 13 53 34

**Comment by ekreerenko** [comment]
> Thank you for doing this cleanup? Are these things that we can define in the lint files to ensure that they are enforced moving forward?

Other code refactoring would be in next PR. Do you want to add some extra lint rules for this project?

**Comment by reustle** [comment]
> Other code refactoring would be in next PR. Do you want to add some extra lint rules for this project?

Yes you can do it in the next PR, thanks.

**Pull request merged**
