### PR TITLE
Added Twemoji To Language Selector

### PR DESCRIPTION
**Pull request by bmaniteja**
@reustle crated this PR incase we decide to go with twemoji.

Screen Shot 2020-04-11 at 5 49 48 PM

https://github.com/reustle/covid19japan/issues/208

### CODE REVIEW

**Comment by reustle** [comment]
Thank you! Just merged the earlier Twemoji PR so that likely cleans up what you need to implement?

**Comment by mertd** [comment]
Since we already have twemoji as a dependency in the package.json, I suggest removing the script tag loading it and using the managed dependency instead by moving the twemoji.parse call into an appropriate JS file. :)

**Comment by reustle** [comment]
Hey, merged the new header PR, I think this PR can be simplified now? Thanks!

**Comment by reustle** [comment]
Hey @mertd would you please be able to suggest some changes on this one, or launch a new one as this one has been silent for 10~ days?

Thanks to you both!

**Comment by mertd** [comment]
@reustle If this is inactive, I could open another PR. I would include some changes to populate the language selection from the central array so that adding new languages doesn't require changes in the selector as well. Thoughts?

**Comment by reustle** [comment]
Sounds good, thanks. We can also incorporate that into #218 then too.

**Pull request closed without merging**
