### PR TITLE
Updating ranges of number of cases in the legend

### PR DESCRIPTION
**Pull request by alsdia**
By using as ranges 1-100, 101-500, 501-1000, 1001+ we can get a better appreciation of the color gradients between prefectures.

### CODE REVIEW

**Comment by colinthornton** [comment]
https://github.com/reustle/covid19japan/issues/183 related

**Comment by Kay-Cube** [comment]
@liquidx 
A new 5 level scale & color code:
**>1000**         RGB(114,4,5)           #720405
**500 ~ 999**  RGB(176,1,13)         #B0010D
**100 ~ 499**   RGB(245,67,54)     #F54336
**50 ~ 99**       RGB(251,155,127)  #FB9B7F
**1 ~ 49**          RGB(254,234,203) #FEEACB

**Comment by liquidx** [comment]
@alsdia would you be able to update your PR with the suggested colors and ranges?

**Comment by alsdia** [comment]
> @alsdia would you be able to update your PR with the suggested colors and ranges?

OK I started to update the files in my local machine with the suggested ranges and I get the following map. I still need to fix the color of the square next to "1000+ cases" that keeps showing up black 0,0,0 instead of (114,4,5). When fixed, I will update my PR.  
image

**Comment by alsdia** [comment]
Understood the reason of the black square I was getting in the legend of the image in my previous comment, I forgot to "add span.five {  color: #720405;}"  in src/i18n/en.json
Now the colors coincide:
image

**Comment by liquidx** [comment]
Thanks, that's looking good. Unfortunately, there are some merge conflicts that's preventing me from merging the PR. If you can resolve them, then I'll merge it.

**Comment by alsdia** [comment]
conflicts now solved.

**Comment by liquidx** [comment]
Thanks so much!

**Pull request merged**
